### How to use this document
# 1. Fill in your info
# 2. Re-excecute the build in the command line with: bundle exec jekyll serve
# 3. Push to github
# NOTE: it looks like you need to rebuild + repush everytime you update this _config.yml file

### Site Settings ###
title               : PossibleCorg 
description         : >-
                      I may or may not be a corgi.
baseurl             : ""   # Change to empty quotes if you are hosting your site at <your-yuwei97910>.github.io directly,
#                                             otherwise will be hosted at <your-yuwei97910>.github.io/{{base_url}}
repository          : jnaiman               # Change to <your-yuwei97910>/<your-yuwei97910>.github.io (or remove it if you don't need remote projects)
open_new_tab        : false                             # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-paginate-v2
  - mini_magick

### To specify which port to host locally on -- use if you have multiple sites you want to host 
# port: 4008

### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**                           # For Documentation Only


### Author Info ###
author:
  name              : YuWei Lai
  image             : https://dogtime.com/assets/uploads/gallery/pembroke-welsh-corgi-dog-breed-pictures/prance-8.jpg
  behance           : yuwei97910
# dribbble          : yuwei97910
  email             : yuwei97910@gmail.com
  facebook          : yuwei97910
  github            : jnaiman # JPN
# gitlab            : yuwei97910
# instagram         : yuwei97910
# kaggle            : yuwei97910
  linkedin          : yuwei97910
  medium            : yuwei97910
# soundcloud        : yuwei97910
# spotify           : yuwei97910
# stackoverflow     : your_user_id
# tumblr            : yuwei97910.tumblr.com
  twitch            : yuwei97910
  twitter           : yuwei97910
  vimeo             : yuwei97910
  youtube           : yuwei97910
# keybase           : yuwei97910


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:                                             # For Documentation Only
    output: true                                        # For Documentation Only


### Disqus ###
disqus:
  shortname: YL                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: false
  username: yuwei97910
  color: "#007bff"
  message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:                                              # For Documentation Only
      path: ""                                          # For Documentation Only
      type: "elements"                                  # For Documentation Only
    values:                                             # For Documentation Only
      layout: "element"                                 # For Documentation Only
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
## Add yours here if you have other stuff in your github.io page!!!**
exclude:
  - README.md
  - README.md~
  - CONTRIBUTING.md
  - LICENSE.md
  - LICENSE.md~
  - config.yml~
  - "*.log"
  - "*.ipynb"
  - "python_notebooks/*"
